### PR TITLE
add delete playlist button

### PR DESCRIPTION
**Pull request by cmrschwarz**
This adds a button in the playlist menu to delete a playlist on the server.
For that purpose a new DELETE HTTP Request was added that deletes a playlist of the given name if present. 
It also deletes the older 'timestamped' versions of that playlist.
Since D(elete), X, E(rase)  were already taken I didn't add a hotkey for this.
I don't really think its necessary, but if you think it is we might use Shift D or the 'Del' key or rebind something else.
Happy do amend that in case.

### CODE REVIEW

**Comment by ltGuillaume** [comment]
The PHP part and JS deletePlaylist(name) is great, but I think we'd be better off by just adding a delete button to the existing playlists menu. Less clutter/"doubled" code.

**Comment by cmrschwarz** [comment]
Ah, you mean inside the "Load" submenu?
Should we rename that button then? To what though? :laughing: : I guess keeping as Load it is fine too.
From a code duplication standpoint the current solution doesn't look bad at all to me, 
but if you prefer the UI feel (which should really be the deciding factor here imho)
of having it inside the existing submenu I can try implementing that or give you push access to this branch.
Whats your call?

**Comment by ltGuillaume** [comment]
I suppose the best way to go about this is to merge Load/Save into Playlists, with at the top an input field and a save button, then below that the saved playlists with an extra delete button (on non-touch devices the button can appear on hover).

**Comment by cmrschwarz** [comment]
That's makes sense as well, and I can implement that it if you decide that it's the best solution, 
but if you want my honest opinion: popups are always a pain. 
They are annoying to use on mobile and having to track wether they are currently open is 
additional work in the code.
Therefore using them sparingly and keeping them as simple as possible
(like we currently do, just a simple list for every one) seems like good design to me.
Also that seems like a big UI change, I'm just a poor C programmer that wants to help out a nice music player :smirk_cat: :,
not sure if i could quickly do that, especially the appear and disappear on non mobile part.

As I see it those are our options:

1. merge as is (Load Btn, Save Btn, Delete Btn) -> Simple
2. implement your first suggestion (Load btn with trash icons on each element (maybe the fade thing), Save Btn) -> Medium Effort
3. implement your second suggestion (Merge 3 Playlist Buttons into a Popup UI with input field + saveBtn + list with delete Btns) -> High Effort

My ranking is just like the effort ranking: 1 > 2 > 3. KISS and so forth.
Of course all Options are viable, and your project -> your decision !
Just let me know what you want and I will get on it :smile:

**Comment by ltGuillaume** [comment]
What do you think of https://github.com/ltGuillaume/MusicFolderPlayer/commit/965100cdce153f8951ffca85984af07117b7c93d?

**Comment by cmrschwarz** [comment]
Sure, that works :+1:  A bit less intuitive, but it's a rare operation and this keeps the UI lean and mean so that's a win. 
Closing this.

**Comment by ltGuillaume** [comment]
Yes you're totally right about that. On desktops it's easy enough (just hover anywhere and you'll see a tooltip), but for touch devices you'd need to be able to find out another way. I'm too lazy to create proper documentation, though 😊

**Pull request closed without merging**
