### PR TITLE
Make client default options configurable from music.ini

### PR DESCRIPTION
**Pull request by cmrschwarz**
This change just allows the admin to configure the default values for some of the UI options
 (Enque, Crossfade, Random and After playlist).

Since I often have to switch setups and loose the browser's local storage that way
it got slightly annoying that these reset every time.

So in the spirit of the GPL here are my changes.

Thank you for the great Sofware!

### CODE REVIEW

**Comment by ltGuillaume** [comment]
Thanks, this is a good idea. I'm gonna move around the settings a little bit soon, anyway, so I'll include your changes as well 🙂

**Comment by cmrschwarz** [comment]
All right :+1:. I guess we can just leave this open till then?
Do I gather that you are currently doing some major refactorings?
I was originally planning on doing a little more stuff like adding deletion of playlists and specific playlist entries,
so if this is a bad time for contributions please let me know, so I can avoid annoying you with open pull requests 
at risk of imminent invalidation.
Thanks in advance :smile:

**Comment by ltGuillaume** [comment]
No big changes, but I'll do them today, so pull requests are welcome 😄

Removing playlists is a good one indeed. Removing entries from the playlist is already possible by dragging, but I need to check if drag 'n drop is finally fixed in Firefox mobile's new (Fenix) versions.

**Comment by ltGuillaume** [comment]
I'm 11 commits ahead in branch https://github.com/ltGuillaume/MusicFolderPlayer/tree/regexp (will be merged with master soon) and added the changes as you proposed a bit differently): https://github.com/ltGuillaume/MusicFolderPlayer/commit/7a8816a68056bba4c9b8c3008d2029d4d28b34e3

**Pull request closed without merging**
